### ISSUE TITLE
Question regarding cosine similarity in Eqn. 3

### ISSUE THREAD

**Issue by Pixie8888** [PaulAlbert31/SNCF#2]
Hi,
Thanks for releasing the code. I have a question regarding the pair wise cosine similarity in eqn.3 in the paper. It's possible S_ij < 0 since the range of cosine similarity is [-1,1]. But as far as I know, the spectra clustering requires the affinity matrix to be non-negative. How do you handle this?

**Comment by PaulAlbert31** [comment]
Hello,
Your interest in our work is much appreciated.
Thank you for raising this issue, because we only look at the 50 most similar neighbors to compute the affinities, the cosine similarities are always positive in the cases we tested even for OOD data. This could indeed become a problem in the case where very little samples are available for a very visually different class. In this case, using the cosine distance (1-cosine similarity) might be better suited.
